// Generated by gencpp from file tb3_projet_LAKHAL_MEZOUAR/MoveGoal.msg
// DO NOT EDIT!


#ifndef TB3_PROJET_LAKHAL_MEZOUAR_MESSAGE_MOVEGOAL_H
#define TB3_PROJET_LAKHAL_MEZOUAR_MESSAGE_MOVEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tb3_projet_LAKHAL_MEZOUAR
{
template <class ContainerAllocator>
struct MoveGoal_
{
  typedef MoveGoal_<ContainerAllocator> Type;

  MoveGoal_()
    : pos_x(0.0)  {
    }
  MoveGoal_(const ContainerAllocator& _alloc)
    : pos_x(0.0)  {
  (void)_alloc;
    }



   typedef float _pos_x_type;
  _pos_x_type pos_x;





  typedef boost::shared_ptr< ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MoveGoal_

typedef ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<std::allocator<void> > MoveGoal;

typedef boost::shared_ptr< ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal > MoveGoalPtr;
typedef boost::shared_ptr< ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal const> MoveGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tb3_projet_LAKHAL_MEZOUAR

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'tb3_projet_LAKHAL_MEZOUAR': ['/home/user/catkin_ws/src/tb3_projet_LAKHAL_MEZOUAR/msg', '/home/user/catkin_ws/devel/share/tb3_projet_LAKHAL_MEZOUAR/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50af954e3a6166bcff3595939a3eeabb";
  }

  static const char* value(const ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50af954e3a6166bcULL;
  static const uint64_t static_value2 = 0xff3595939a3eeabbULL;
};

template<class ContainerAllocator>
struct DataType< ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tb3_projet_LAKHAL_MEZOUAR/MoveGoal";
  }

  static const char* value(const ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
float32 pos_x  # position cible\n\
";
  }

  static const char* value(const ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tb3_projet_LAKHAL_MEZOUAR::MoveGoal_<ContainerAllocator>& v)
  {
    s << indent << "pos_x: ";
    Printer<float>::stream(s, indent + "  ", v.pos_x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TB3_PROJET_LAKHAL_MEZOUAR_MESSAGE_MOVEGOAL_H
